export type Capability = "chat" | "coding" | "vision" | "tamil" | "uncensored" | "reasoning" | "tool_use";

export type ModelVariant = {
  id: string;
  name: string;
  shortName: string;
  description: string;
  sizeLabel: string;
  sizeBytes: number;
  ramRequiredGb: number;
  quantization: string;
  format: "gguf" | "task";
  downloadUrl: string;
  badges: string[];
  recommended?: boolean;
  ramWarning?: boolean;
  capabilities?: Capability[];
};

export const GEMMA_MODELS: ModelVariant[] = [
  // ─── Google Gemma 3 Series ───────────────────────────────────────────────
  {
    id: "gemma-3-270m-it-q4",
    name: "Gemma 3 270M Instruct",
    shortName: "Gemma 3 270M",
    description: "Ultra-tiny Gemma 3. Runs on any device with minimal RAM. Best for simple Q&A on very low-end phones.",
    sizeLabel: "~200 MB",
    sizeBytes: 200_000_000,
    ramRequiredGb: 1,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/bartowski/google_gemma-3-270m-it-GGUF/resolve/main/google_gemma-3-270m-it-Q4_K_M.gguf",
    badges: ["GGUF", "Tiny", "Q4_K_M"],
    capabilities: ["chat"],
  },
  {
    id: "gemma-3-1b-it-q4",
    name: "Gemma 3 1B Instruct",
    shortName: "Gemma 3 1B",
    description: "Smallest Gemma 3 variant. Runs on almost any modern phone. Great for quick prompts and low-RAM devices.",
    sizeLabel: "~720 MB",
    sizeBytes: 720_000_000,
    ramRequiredGb: 2,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/unsloth/gemma-3-1b-it-GGUF/resolve/main/gemma-3-1b-it-Q4_K_M.gguf",
    badges: ["GGUF", "Tiny"],
    capabilities: ["chat"],
  },
  {
    id: "gemma-3-4b-it-q4",
    name: "Gemma 3 4B Instruct",
    shortName: "Gemma 3 4B",
    description: "A balanced mid-size model. Good answer quality with reasonable size for most modern Android phones.",
    sizeLabel: "~2.5 GB",
    sizeBytes: 2_500_000_000,
    ramRequiredGb: 4,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/unsloth/gemma-3-4b-it-GGUF/resolve/main/gemma-3-4b-it-Q4_K_M.gguf",
    badges: ["GGUF", "Balanced"],
    capabilities: ["chat"],
  },
  // ─── Google Gemma 3n Series ──────────────────────────────────────────────
  {
    id: "gemma-3n-e2b-it-q4",
    name: "Gemma 3n E2B Instruct",
    shortName: "Gemma 3n E2B",
    description: "Lightweight on-device chat model. Faster responses, perfect for everyday conversations and coding questions.",
    sizeLabel: "~3.1 GB",
    sizeBytes: 3_100_000_000,
    ramRequiredGb: 4,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/unsloth/gemma-3n-E2B-it-GGUF/resolve/main/gemma-3n-E2B-it-Q4_K_M.gguf",
    badges: ["GGUF", "Chat", "Q4_K_M"],
    recommended: true,
    capabilities: ["chat"],
  },
  {
    id: "gemma-3n-e4b-it-q4",
    name: "Gemma 3n E4B Instruct",
    shortName: "Gemma 3n E4B",
    description: "Stronger reasoning and longer answers. Larger model size with slower first load but more complete responses.",
    sizeLabel: "~4.9 GB",
    sizeBytes: 4_900_000_000,
    ramRequiredGb: 6,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/unsloth/gemma-3n-E4B-it-GGUF/resolve/main/gemma-3n-E4B-it-Q4_K_M.gguf",
    badges: ["GGUF", "Chat", "Q4_K_M"],
    ramWarning: true,
    capabilities: ["chat"],
  },
  // ─── Google Gemma 4 Series ───────────────────────────────────────────────
  {
    id: "gemma-4-e2b-it-q4",
    name: "Gemma 4 E2B Instruct",
    shortName: "Gemma 4 E2B",
    description: "Latest Gemma 4 compact model. Better instruction following and improved reasoning over Gemma 3n.",
    sizeLabel: "~3.2 GB",
    sizeBytes: 3_200_000_000,
    ramRequiredGb: 5,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/unsloth/gemma-4-e2b-it-GGUF/resolve/main/gemma-4-e2b-it-Q4_K_M.gguf",
    badges: ["GGUF", "NEW", "Q4_K_M"],
    capabilities: ["chat", "reasoning"],
  },
  {
    id: "gemma-4-e4b-it-q4",
    name: "Gemma 4 E4B Instruct",
    shortName: "Gemma 4 E4B",
    description: "Larger Gemma 4 model with superior reasoning and longer context. Best Gemma model for demanding tasks.",
    sizeLabel: "~5.0 GB",
    sizeBytes: 5_000_000_000,
    ramRequiredGb: 7,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/unsloth/gemma-4-e4b-it-GGUF/resolve/main/gemma-4-e4b-it-Q4_K_M.gguf",
    badges: ["GGUF", "NEW", "Q4_K_M"],
    ramWarning: true,
    capabilities: ["chat", "reasoning"],
  },
  // ─── Qwen 2.5 VL (Vision Language) ──────────────────────────────────────
  {
    id: "qwen2.5-vl-3b-q4",
    name: "Qwen 2.5 VL 3B Instruct",
    shortName: "Qwen 2.5 VL 3B",
    description: "Vision-language model. Can understand images and answer questions about them. Balanced size.",
    sizeLabel: "~2.0 GB",
    sizeBytes: 2_000_000_000,
    ramRequiredGb: 4,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/bartowski/Qwen2.5-VL-3B-Instruct-GGUF/resolve/main/Qwen2.5-VL-3B-Instruct-Q4_K_M.gguf",
    badges: ["GGUF", "Vision", "Q4_K_M"],
    capabilities: ["chat", "vision", "tool_use"],
  },
  {
    id: "qwen2.5-vl-7b-q4",
    name: "Qwen 2.5 VL 7B Instruct",
    shortName: "Qwen 2.5 VL 7B",
    description: "Powerful vision-language model. Advanced image understanding, OCR, charts, and diagrams. Excellent tool use.",
    sizeLabel: "~4.5 GB",
    sizeBytes: 4_500_000_000,
    ramRequiredGb: 6,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/bartowski/Qwen2.5-VL-7B-Instruct-GGUF/resolve/main/Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf",
    badges: ["GGUF", "Vision", "Q4_K_M"],
    ramWarning: true,
    capabilities: ["chat", "vision", "tool_use"],
  },
  // ─── Qwen 3 VL (Vision Language) ─────────────────────────────────────────
  {
    id: "qwen3-vl-2b-q4",
    name: "Qwen 3 VL 2B Instruct",
    shortName: "Qwen 3 VL 2B",
    description: "Latest Qwen 3 vision model. See and analyze images, screenshots, charts. Compact size with strong vision.",
    sizeLabel: "~1.5 GB",
    sizeBytes: 1_500_000_000,
    ramRequiredGb: 3,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/bartowski/Qwen3-VL-2B-Instruct-GGUF/resolve/main/Qwen3-VL-2B-Instruct-Q4_K_M.gguf",
    badges: ["GGUF", "Vision", "NEW"],
    capabilities: ["chat", "vision", "tool_use", "reasoning"],
  },
  {
    id: "qwen3-vl-4b-q4",
    name: "Qwen 3 VL 4B Instruct",
    shortName: "Qwen 3 VL 4B",
    description: "Mid-size Qwen 3 vision model. Stronger image reasoning, better at text extraction and visual QA.",
    sizeLabel: "~2.5 GB",
    sizeBytes: 2_500_000_000,
    ramRequiredGb: 4,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/bartowski/Qwen3-VL-4B-Instruct-GGUF/resolve/main/Qwen3-VL-4B-Instruct-Q4_K_M.gguf",
    badges: ["GGUF", "Vision", "NEW"],
    capabilities: ["chat", "vision", "tool_use", "reasoning"],
  },
  {
    id: "qwen3-vl-8b-q4",
    name: "Qwen 3 VL 8B Instruct",
    shortName: "Qwen 3 VL 8B",
    description: "Largest Qwen 3 vision model. Best image understanding, document analysis, and visual reasoning.",
    sizeLabel: "~5.0 GB",
    sizeBytes: 5_000_000_000,
    ramRequiredGb: 7,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/bartowski/Qwen3-VL-8B-Instruct-GGUF/resolve/main/Qwen3-VL-8B-Instruct-Q4_K_M.gguf",
    badges: ["GGUF", "Vision", "NEW"],
    ramWarning: true,
    capabilities: ["chat", "vision", "tool_use", "reasoning"],
  },
  // ─── Qwen 3 Text Series ───────────────────────────────────────────────────
  {
    id: "qwen3-4b-q4",
    name: "Qwen 3 4B Instruct",
    shortName: "Qwen 3 4B",
    description: "Compact Qwen 3 with thinking mode. Switch between fast chat and slow deep-reasoning on demand.",
    sizeLabel: "~2.5 GB",
    sizeBytes: 2_500_000_000,
    ramRequiredGb: 4,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/unsloth/Qwen3-4B-GGUF/resolve/main/Qwen3-4B-Q4_K_M.gguf",
    badges: ["GGUF", "Thinking", "Q4_K_M"],
    capabilities: ["chat", "reasoning", "tool_use", "coding"],
  },
  {
    id: "qwen3-8b-q4",
    name: "Qwen 3 8B Instruct",
    shortName: "Qwen 3 8B",
    description: "Strong all-rounder with built-in thinking mode. Great for code, math, and complex multi-step tasks.",
    sizeLabel: "~5.0 GB",
    sizeBytes: 5_000_000_000,
    ramRequiredGb: 6,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/unsloth/Qwen3-8B-GGUF/resolve/main/Qwen3-8B-Q4_K_M.gguf",
    badges: ["GGUF", "Thinking", "Q4_K_M"],
    ramWarning: true,
    capabilities: ["chat", "reasoning", "tool_use", "coding"],
  },
  {
    id: "qwen3-14b-q4",
    name: "Qwen 3 14B Instruct",
    shortName: "Qwen 3 14B",
    description: "Large Qwen 3 for demanding reasoning and coding. Needs 10GB+ RAM. Best for high-end flagship phones.",
    sizeLabel: "~8.5 GB",
    sizeBytes: 8_500_000_000,
    ramRequiredGb: 12,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/unsloth/Qwen3-14B-GGUF/resolve/main/Qwen3-14B-Q4_K_M.gguf",
    badges: ["GGUF", "Large", "Q4_K_M"],
    ramWarning: true,
    capabilities: ["chat", "reasoning", "tool_use", "coding"],
  },
  {
    id: "qwen3-4b-2507-q4",
    name: "Qwen 3 4B 2507",
    shortName: "Qwen 3 4B 2507",
    description: "Updated July 2025 Qwen 3 4B. Improved instruction following and reasoning over the original.",
    sizeLabel: "~2.5 GB",
    sizeBytes: 2_500_000_000,
    ramRequiredGb: 4,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/unsloth/Qwen3-4B-2507-GGUF/resolve/main/Qwen3-4B-2507-Q4_K_M.gguf",
    badges: ["GGUF", "2507", "Q4_K_M"],
    capabilities: ["chat", "reasoning", "tool_use"],
  },
  // ─── Qwen 3.5 Series ─────────────────────────────────────────────────────
  {
    id: "qwen3.5-2b-q4",
    name: "Qwen 3.5 2B Instruct",
    shortName: "Qwen 3.5 2B",
    description: "Compact Qwen 3.5 with improved long-context and better instruction following. Great for low-RAM phones.",
    sizeLabel: "~1.5 GB",
    sizeBytes: 1_500_000_000,
    ramRequiredGb: 3,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/bartowski/Qwen3.5-2B-Instruct-GGUF/resolve/main/Qwen3.5-2B-Instruct-Q4_K_M.gguf",
    badges: ["GGUF", "NEW", "Q4_K_M"],
    capabilities: ["chat", "reasoning", "tool_use"],
  },
  {
    id: "qwen3.5-4b-q4",
    name: "Qwen 3.5 4B Instruct",
    shortName: "Qwen 3.5 4B",
    description: "Balanced Qwen 3.5 model. Improved reasoning and tool use over Qwen 3. Solid choice for most tasks.",
    sizeLabel: "~2.5 GB",
    sizeBytes: 2_500_000_000,
    ramRequiredGb: 4,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/bartowski/Qwen3.5-4B-Instruct-GGUF/resolve/main/Qwen3.5-4B-Instruct-Q4_K_M.gguf",
    badges: ["GGUF", "NEW", "Q4_K_M"],
    capabilities: ["chat", "reasoning", "tool_use"],
  },
  {
    id: "qwen3.5-9b-q4",
    name: "Qwen 3.5 9B Instruct",
    shortName: "Qwen 3.5 9B",
    description: "Larger Qwen 3.5 with excellent reasoning and multi-step tool calling. For flagship phones.",
    sizeLabel: "~5.5 GB",
    sizeBytes: 5_500_000_000,
    ramRequiredGb: 8,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/bartowski/Qwen3.5-9B-Instruct-GGUF/resolve/main/Qwen3.5-9B-Instruct-Q4_K_M.gguf",
    badges: ["GGUF", "NEW", "Q4_K_M"],
    ramWarning: true,
    capabilities: ["chat", "reasoning", "tool_use", "coding"],
  },
  // ─── Mistral / Ministral ─────────────────────────────────────────────────
  {
    id: "ministral-3b-q4",
    name: "Ministral 3 3B Instruct",
    shortName: "Ministral 3 3B",
    description: "Mistral's compact 3B model with strong tool use. Multilingual, fast inference, good for assistant tasks.",
    sizeLabel: "~2.0 GB",
    sizeBytes: 2_000_000_000,
    ramRequiredGb: 4,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/bartowski/Ministral-3B-instruct-2503-GGUF/resolve/main/Ministral-3B-instruct-2503-Q4_K_M.gguf",
    badges: ["GGUF", "Tool Use", "Q4_K_M"],
    capabilities: ["chat", "tool_use"],
  },
  {
    id: "ministral-3b-reasoning-q4",
    name: "Ministral 3 3B Reasoning",
    shortName: "Ministral 3B Reason",
    description: "Reasoning-focused Ministral 3B. Chain-of-thought thinking for math, logic, and analysis tasks.",
    sizeLabel: "~2.0 GB",
    sizeBytes: 2_000_000_000,
    ramRequiredGb: 4,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/bartowski/Ministral-3B-reasoning-GGUF/resolve/main/Ministral-3B-reasoning-Q4_K_M.gguf",
    badges: ["GGUF", "Reasoning", "Q4_K_M"],
    capabilities: ["chat", "reasoning"],
  },
  {
    id: "ministral-8b-q4",
    name: "Ministral 3 8B Instruct",
    shortName: "Ministral 3 8B",
    description: "Mistral's powerful 8B model. Strong multilingual support, function calling, and long context.",
    sizeLabel: "~4.7 GB",
    sizeBytes: 4_700_000_000,
    ramRequiredGb: 6,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/bartowski/Ministral-8B-Instruct-2410-GGUF/resolve/main/Ministral-8B-Instruct-2410-Q4_K_M.gguf",
    badges: ["GGUF", "Tool Use", "Q4_K_M"],
    ramWarning: true,
    capabilities: ["chat", "tool_use", "coding"],
  },
  {
    id: "ministral-8b-reasoning-q4",
    name: "Ministral 3 8B Reasoning",
    shortName: "Ministral 8B Reason",
    description: "Reasoning-focused Ministral 8B. Deep thinking, step-by-step problem solving. Great for STEM.",
    sizeLabel: "~4.7 GB",
    sizeBytes: 4_700_000_000,
    ramRequiredGb: 6,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/bartowski/Ministral-8B-reasoning-GGUF/resolve/main/Ministral-8B-reasoning-Q4_K_M.gguf",
    badges: ["GGUF", "Reasoning", "Q4_K_M"],
    ramWarning: true,
    capabilities: ["chat", "reasoning"],
  },
  // ─── DeepSeek R1 Series ───────────────────────────────────────────────────
  {
    id: "deepseek-r1-0528-qwen3-8b-q4",
    name: "DeepSeek R1 0528 Qwen3 8B",
    shortName: "R1 0528 Qwen3 8B",
    description: "Latest DeepSeek R1 based on Qwen3. Visible step-by-step reasoning with <think> blocks. Math & coding.",
    sizeLabel: "~5.0 GB",
    sizeBytes: 5_000_000_000,
    ramRequiredGb: 7,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/unsloth/DeepSeek-R1-0528-Qwen3-8B-GGUF/resolve/main/DeepSeek-R1-0528-Qwen3-8B-Q4_K_M.gguf",
    badges: ["GGUF", "Reasoning", "NEW"],
    ramWarning: true,
    capabilities: ["chat", "reasoning", "coding"],
  },
  {
    id: "deepseek-r1-distill-qwen-7b-q4",
    name: "DeepSeek R1 Distill Qwen 7B",
    shortName: "R1 Qwen 7B",
    description: "Distilled reasoning from DeepSeek R1 into compact Qwen 7B. Shows thinking process. Great for analysis.",
    sizeLabel: "~4.4 GB",
    sizeBytes: 4_400_000_000,
    ramRequiredGb: 6,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-7B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf",
    badges: ["GGUF", "Reasoning", "Q4_K_M"],
    ramWarning: true,
    capabilities: ["chat", "reasoning", "coding"],
  },
  {
    id: "deepseek-r1-distill-llama-8b-q4",
    name: "DeepSeek R1 Distill Llama 8B",
    shortName: "R1 Llama 8B",
    description: "Reasoning distilled into Llama 8B. Strong math and code reasoning with chain-of-thought.",
    sizeLabel: "~5.0 GB",
    sizeBytes: 5_000_000_000,
    ramRequiredGb: 7,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/unsloth/DeepSeek-R1-Distill-Llama-8B-GGUF/resolve/main/DeepSeek-R1-Distill-Llama-8B-Q4_K_M.gguf",
    badges: ["GGUF", "Reasoning", "Q4_K_M"],
    ramWarning: true,
    capabilities: ["chat", "reasoning", "coding"],
  },
  {
    id: "deepseek-r1-distill-qwen-14b-q4",
    name: "DeepSeek R1 Distill Qwen 14B",
    shortName: "R1 Qwen 14B",
    description: "Best reasoning distill model. Solves complex math olympiad problems. Needs very high-end phone.",
    sizeLabel: "~8.5 GB",
    sizeBytes: 8_500_000_000,
    ramRequiredGb: 12,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-14B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-14B-Q4_K_M.gguf",
    badges: ["GGUF", "Reasoning", "Large"],
    ramWarning: true,
    capabilities: ["chat", "reasoning", "coding"],
  },
  // ─── Microsoft Phi-4 Series ───────────────────────────────────────────────
  {
    id: "phi-4-mini-reasoning-q4",
    name: "Phi-4 Mini Reasoning",
    shortName: "Phi-4 Mini Reason",
    description: "Microsoft's compact reasoning model. Excellent math and science. Small footprint, strong performance.",
    sizeLabel: "~2.5 GB",
    sizeBytes: 2_500_000_000,
    ramRequiredGb: 4,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/bartowski/Phi-4-mini-reasoning-GGUF/resolve/main/Phi-4-mini-reasoning-Q4_K_M.gguf",
    badges: ["GGUF", "Reasoning", "Microsoft"],
    capabilities: ["chat", "reasoning", "coding"],
  },
  {
    id: "phi-4-reasoning-q4",
    name: "Phi-4 Reasoning",
    shortName: "Phi-4 Reasoning",
    description: "Full Microsoft Phi-4 tuned for deep reasoning. Complex math, science, legal analysis. High-RAM required.",
    sizeLabel: "~9.0 GB",
    sizeBytes: 9_000_000_000,
    ramRequiredGb: 12,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/bartowski/Phi-4-reasoning-GGUF/resolve/main/Phi-4-reasoning-Q4_K_M.gguf",
    badges: ["GGUF", "Reasoning", "Microsoft"],
    ramWarning: true,
    capabilities: ["chat", "reasoning", "coding"],
  },
  {
    id: "phi-4-reasoning-plus-q4",
    name: "Phi-4 Reasoning Plus",
    shortName: "Phi-4 Reason+",
    description: "Enhanced Phi-4 reasoning with RLVR training. State-of-the-art math and science. Flagship phones only.",
    sizeLabel: "~9.0 GB",
    sizeBytes: 9_000_000_000,
    ramRequiredGb: 12,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/bartowski/Phi-4-reasoning-plus-GGUF/resolve/main/Phi-4-reasoning-plus-Q4_K_M.gguf",
    badges: ["GGUF", "Reasoning", "Microsoft"],
    ramWarning: true,
    capabilities: ["chat", "reasoning", "coding"],
  },
  // ─── AllenAI OLMo / OLMoCR ───────────────────────────────────────────────
  {
    id: "olmocr-2-7b-q4",
    name: "OLMoCR 2 7B",
    shortName: "OLMoCR 2 7B",
    description: "AllenAI document OCR model. Extract text from scanned documents, PDFs, and screenshots.",
    sizeLabel: "~4.4 GB",
    sizeBytes: 4_400_000_000,
    ramRequiredGb: 6,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/bartowski/olmocr-2-7b-GGUF/resolve/main/olmocr-2-7b-Q4_K_M.gguf",
    badges: ["GGUF", "Vision", "OCR"],
    ramWarning: true,
    capabilities: ["vision"],
  },
  {
    id: "olmo-3-7b-q4",
    name: "OLMo 3 7B Instruct",
    shortName: "OLMo 3 7B",
    description: "AllenAI's open language model. Strong general purpose chat with transparent training data.",
    sizeLabel: "~4.4 GB",
    sizeBytes: 4_400_000_000,
    ramRequiredGb: 6,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/bartowski/OLMo-3-0125-7B-Instruct-GGUF/resolve/main/OLMo-3-0125-7B-Instruct-Q4_K_M.gguf",
    badges: ["GGUF", "AllenAI", "Q4_K_M"],
    ramWarning: true,
    capabilities: ["chat"],
  },
  {
    id: "olmo-3-7b-think-q4",
    name: "OLMo 3 7B Think",
    shortName: "OLMo 3 7B Think",
    description: "Thinking-focused OLMo 3. Reasoning traces, step-by-step problem solving with visible thought process.",
    sizeLabel: "~4.4 GB",
    sizeBytes: 4_400_000_000,
    ramRequiredGb: 6,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/bartowski/OLMo-3-0125-7B-Think-GGUF/resolve/main/OLMo-3-0125-7B-Think-Q4_K_M.gguf",
    badges: ["GGUF", "Reasoning", "AllenAI"],
    ramWarning: true,
    capabilities: ["chat", "reasoning"],
  },
  // ─── OpenAI Open Source ───────────────────────────────────────────────────
  {
    id: "gpt-oss-20b-q4",
    name: "OpenAI GPT OSS 20B",
    shortName: "GPT OSS 20B",
    description: "OpenAI's open-source 20B model. Strong general chat and reasoning. Requires very high-end hardware.",
    sizeLabel: "~12 GB",
    sizeBytes: 12_000_000_000,
    ramRequiredGb: 16,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/bartowski/openai-gpt-oss-20b-GGUF/resolve/main/openai-gpt-oss-20b-Q4_K_M.gguf",
    badges: ["GGUF", "OpenAI", "Large"],
    ramWarning: true,
    capabilities: ["chat", "reasoning", "tool_use"],
  },
  // ─── Coding Models ────────────────────────────────────────────────────────
  {
    id: "qwen2.5-coder-1.5b-q4",
    name: "Qwen2.5 Coder 1.5B",
    shortName: "Qwen Coder 1.5B",
    description: "Specialized coding model. Supports 92 languages. Fast on low-RAM phones. Great for code generation and debugging.",
    sizeLabel: "~1 GB",
    sizeBytes: 1_000_000_000,
    ramRequiredGb: 2,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF/resolve/main/qwen2.5-coder-1.5b-instruct-q4_k_m.gguf",
    badges: ["GGUF", "Coding", "Q4_K_M"],
    capabilities: ["coding", "tool_use"],
  },
  {
    id: "deepseek-coder-1.3b-q4",
    name: "DeepSeek Coder 1.3B",
    shortName: "DeepSeek Coder",
    description: "Lightweight coding model trained on 2T tokens of code. Excellent for code completion and generation.",
    sizeLabel: "~800 MB",
    sizeBytes: 800_000_000,
    ramRequiredGb: 2,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/TheBloke/deepseek-coder-1.3b-instruct-GGUF/resolve/main/deepseek-coder-1.3b-instruct.Q4_K_M.gguf",
    badges: ["GGUF", "Coding", "Q4_K_M"],
    capabilities: ["coding"],
  },
  // ─── Uncensored ───────────────────────────────────────────────────────────
  {
    id: "llama-3.2-1b-uncensored-q4",
    name: "Llama 3.2 1B Uncensored",
    shortName: "Llama 3.2 Uncensored",
    description: "Uncensored variant of Llama 3.2 1B. No content filters. Use responsibly.",
    sizeLabel: "~800 MB",
    sizeBytes: 800_000_000,
    ramRequiredGb: 2,
    quantization: "Q4_K_M",
    format: "gguf",
    downloadUrl: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-uncensored-GGUF/resolve/main/Llama-3.2-1B-Instruct-uncensored-Q4_K_M.gguf",
    badges: ["GGUF", "Uncensored", "Q4_K_M"],
    capabilities: ["chat", "uncensored"],
  },
];

export function findModel(id: string): ModelVariant | undefined {
  return GEMMA_MODELS.find((m) => m.id === id);
}

export function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  if (bytes < 1024 * 1024 * 1024) return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  return `${(bytes / (1024 * 1024 * 1024)).toFixed(2)} GB`;
}

export function getRecommendedModel(ramGb: number): ModelVariant {
  if (ramGb <= 2) return GEMMA_MODELS.find((m) => m.id === "gemma-3-1b-it-q4")!;
  if (ramGb <= 3) return GEMMA_MODELS.find((m) => m.id === "gemma-3-4b-it-q4")!;
  return GEMMA_MODELS.find((m) => m.id === "gemma-3n-e2b-it-q4")!;
}
